import type { Metadata } from "next";
import { DM_Serif_Text } from "next/font/google";
import "./globals.scss";
// components:
import Navbar from "./components/navbar/navbar";

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

const font = DM_Serif_Text({
  preload: true,
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eport function fetchNavData(){}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
